In [8]:
import numpy as np
import pandas as pd
from  matplotlib import pyplot as plt
import warnings

In [9]:
warnings.filterwarnings('ignore')

In [10]:
df=pd.read_csv('BitcoinPrice.csv')

In [11]:
df.head()

                  Date        Price
0  2018-08-25 00:00:00  6719.429231
1  2018-08-26 00:00:00  6673.274167
2  2018-08-27 00:00:00  6719.266154
3  2018-08-28 00:00:00  7000.040000
4  2018-08-29 00:00:00  7054.276429

In [12]:
df.drop(['Date'],1,inplace=True)

In [13]:
df.head()

         Price
0  6719.429231
1  6673.274167
2  6719.266154
3  7000.040000
4  7054.276429

In [14]:
p_day=30

In [15]:
df['Predection']=df[['Price']].shift(-p_day)

In [16]:
df.head()

         Price   Predection
0  6719.429231  6639.304167
1  6673.274167  6412.459167
2  6719.266154  6468.631667
3  7000.040000  6535.476667
4  7054.276429  6677.342500

In [17]:
X=np.array(df.drop(['Predection'],1))

In [18]:
X=X[:len(df)-p_day]

In [19]:
X.shape

(335, 1)

In [20]:
X

array([[ 6719.42923077],
       [ 6673.27416667],
       [ 6719.26615385],
       [ 7000.04      ],
       [ 7054.27642857],
       [ 6932.6625    ],
       [ 6981.94615385],
       [ 7100.94666667],
       [ 7247.93538462],
       [ 7260.94923077],
       [ 7326.8525    ],
       [ 7113.06923077],
       [ 6433.27166667],
       [ 6444.80416667],
       [ 6366.1075    ],
       [ 6286.42583333],
       [ 6297.87769231],
       [ 6296.32083333],
       [ 6273.1375    ],
       [ 6450.17923077],
       [ 6499.0625    ],
       [ 6518.655     ],
       [ 6480.64416667],
       [ 6400.60083333],
       [ 6296.63166667],
       [ 6335.82666667],
       [ 6418.56266667],
       [ 6669.99083333],
       [ 6709.3125    ],
       [ 6710.445     ],
       [ 6639.30416667],
       [ 6412.45916667],
       [ 6468.63166667],
       [ 6535.47666667],
       [ 6677.3425    ],
       [ 6550.47416667],
       [ 6593.135     ],
       [ 6590.96833333],
       [ 6562.64166667],
       [ 6470.4025    ],
       [ 6563.62833333],
       [ 6568.54916667],
       [ 6581.48666667],
       [ 6558.5375    ],
       [ 6618.56769231],
       [ 6621.71166667],
       [ 6563.00916667],
       [ 6248.63583333],
       [ 6260.53083333],
       [ 6260.64583333],
       [ 6299.39916667],
       [ 6452.57166667],
       [ 6596.61833333],
       [ 6596.27615385],
       [ 6568.04076923],
       [ 6487.44416667],
       [ 6488.82583333],
       [ 6531.60166667],
       [ 6498.48583333],
       [ 6481.426     ],
       [ 6508.31      ],
       [ 6478.0825    ],
       [ 6473.75333333],
       [ 6465.9175    ],
       [ 6448.22166667],
       [ 6382.66833333],
       [ 6309.45285714],
       [ 6310.28416667],
       [ 6342.28083333],
       [ 6387.67416667],
       [ 6363.79583333],
       [ 6391.87333333],
       [ 6436.965     ],
       [ 6445.35416667],
       [ 6538.79      ],
       [ 6486.25166667],
       [ 6411.28083333],
       [ 6399.03333333],
       [ 6378.26833333],
       [ 6401.93666667],
       [ 6372.06333333],
       [ 6176.155     ],
       [ 5615.18      ],
       [ 5596.1925    ],
       [ 5558.24333333],
       [ 5606.04416667],
       [ 5303.9425    ],
       [ 4671.97      ],
       [ 4533.68083333],
       [ 4548.7975    ],
       [ 4309.3375    ],
       [ 4293.84083333],
       [ 3823.51166667],
       [ 3920.53666667],
       [ 3751.66833333],
       [ 4103.45384615],
       [ 4263.78333333],
       [ 4106.87166667],
       [ 4116.7775    ],
       [ 4167.54666667],
       [ 3967.52416667],
       [ 3961.49333333],
       [ 3858.34916667],
       [ 3742.94333333],
       [ 3405.64333333],
       [ 3435.34      ],
       [ 3528.80333333],
       [ 3523.96      ],
       [ 3426.19      ],
       [ 3462.04      ],
       [ 3406.7625    ],
       [ 3278.37416667],
       [ 3225.29916667],
       [ 3271.23833333],
       [ 3392.405     ],
       [ 3567.47      ],
       [ 3808.0425    ],
       [ 3982.85083333],
       [ 4015.60916667],
       [ 3910.97333333],
       [ 4027.47833333],
       [ 4178.59083333],
       [ 3813.88      ],
       [ 3825.37916667],
       [ 3747.83916667],
       [ 3743.905     ],
       [ 3912.28583333],
       [ 3832.92166667],
       [ 3791.54583333],
       [ 3752.27166667],
       [ 3867.13833333],
       [ 3865.7975    ],
       [ 3822.62666667],
       [ 3868.4875    ],
       [ 3920.45666667],
       [ 4036.09333333],
       [ 4035.855     ],
       [ 4034.13833333],
       [ 3812.58583333],
       [ 3656.73583333],
       [ 3646.34583333],
       [ 3599.84166667],
       [ 3604.1175    ],
       [ 3656.785     ],
       [ 3621.27083333],
       [ 3619.96416667],
       [ 3632.395     ],
       [ 3690.52333333],
       [ 3620.1275    ],
       [ 3548.4275    ],
       [ 3558.92416667],
       [ 3579.89666667],
       [ 3567.29916667],
       [ 3572.735     ],
       [ 3589.26083333],
       [ 3567.76333333],
       [ 3458.06666667],
       [ 3417.1675    ],
       [ 3452.22333333],
       [ 3454.00882353],
       [ 3454.19461538],
       [ 3470.07916667],
       [ 3468.305     ],
       [ 3452.32833333],
       [ 3458.70333333],
       [ 3406.82083333],
       [ 3403.96416667],
       [ 3498.86833333],
       [ 3652.21166667],
       [ 3645.27666667],
       [ 3634.77      ],
       [ 3624.15583333],
       [ 3623.07166667],
       [ 3609.86916667],
       [ 3610.74833333],
       [ 3630.39666667],
       [ 3631.55333333],
       [ 3810.78153846],
       [ 3933.14333333],
       [ 3951.565     ],
       [ 3948.41166667],
       [ 3968.65666667],
       [ 4018.04416667],
       [ 4020.12583333],
       [ 3829.56833333],
       [ 3833.31083333],
       [ 3832.61307692],
       [ 3843.58333333],
       [ 3842.13916667],
       [ 3827.4875    ],
       [ 3827.69083333],
       [ 3749.56833333],
       [ 3793.26083333],
       [ 3863.33333333],
       [ 3888.70166667],
       [ 3905.05833333],
       [ 3919.56583333],
       [ 3922.615     ],
       [ 3896.71833333],
       [ 3880.7675    ],
       [ 3881.37923077],
       [ 3883.98928571],
       [ 3918.08666667],
       [ 4011.0925    ],
       [ 3994.34833333],
       [ 3998.4975    ],
       [ 4008.65833333],
       [ 4025.02583333],
       [ 4026.63583333],
       [ 4000.335     ],
       [ 4006.11583333],
       [ 3995.32333333],
       [ 3977.45416667],
       [ 3933.95416667],
       [ 4011.36583333],
       [ 4034.05666667],
       [ 4075.52642857],
       [ 4107.34083333],
       [ 4109.31666667],
       [ 4145.10846154],
       [ 4675.1125    ],
       [ 5018.49833333],
       [ 4970.84916667],
       [ 4980.89833333],
       [ 5042.51769231],
       [ 5126.83416667],
       [ 5214.27666667],
       [ 5197.75076923],
       [ 5251.19      ],
       [ 5111.77076923],
       [ 5031.475     ],
       [ 5076.3       ],
       [ 5077.805     ],
       [ 5114.85416667],
       [ 5109.94666667],
       [ 5214.57416667],
       [ 5263.3975    ],
       [ 5255.61416667],
       [ 5302.9575    ],
       [ 5274.14583333],
       [ 5305.275     ],
       [ 5527.80166667],
       [ 5465.515     ],
       [ 5421.52666667],
       [ 5280.61666667],
       [ 5281.80916667],
       [ 5306.695     ],
       [ 5277.88333333],
       [ 5262.36333333],
       [ 5310.17333333],
       [ 5364.99166667],
       [ 5633.7475    ],
       [ 5697.92333333],
       [ 5718.22916667],
       [ 5654.35333333],
       [ 5863.52333333],
       [ 5851.67076923],
       [ 6056.4175    ],
       [ 6302.6125    ],
       [ 6833.35083333],
       [ 7152.48416667],
       [ 7447.11416667],
       [ 8005.25083333],
       [ 8063.89583333],
       [ 7979.575     ],
       [ 7265.96333333],
       [ 7338.52083333],
       [ 7894.92666667],
       [ 7926.705     ],
       [ 7954.80833333],
       [ 7896.51083333],
       [ 7688.52583333],
       [ 7972.71916667],
       [ 8046.10769231],
       [ 8114.9325    ],
       [ 8779.97083333],
       [ 8727.90083333],
       [ 8646.195     ],
       [ 8641.89166667],
       [ 8342.77      ],
       [ 8543.03      ],
       [ 8663.6425    ],
       [ 8546.17166667],
       [ 7848.41583333],
       [ 7765.68833333],
       [ 7756.9575    ],
       [ 7920.945     ],
       [ 7941.22166667],
       [ 7817.76833333],
       [ 7815.13583333],
       [ 7914.53916667],
       [ 8033.30666667],
       [ 8163.66333333],
       [ 8342.24076923],
       [ 8721.645     ],
       [ 9096.28583333],
       [ 9227.125     ],
       [ 9160.0675    ],
       [ 9147.005     ],
       [ 9346.0725    ],
       [ 9791.0175    ],
       [10730.39166667],
       [10748.01166667],
       [10851.84833333],
       [11314.76153846],
       [12686.38833333],
       [11834.12416667],
       [11665.57583333],
       [11886.88615385],
       [11545.63333333],
       [10690.83333333],
       [10300.4875    ],
       [11342.3175    ],
       [11779.45083333],
       [11118.8875    ],
       [11411.61666667],
       [11310.50666667],
       [11788.06916667],
       [12567.70384615],
       [12668.62916667],
       [11560.6025    ],
       [11577.69538462],
       [11412.12416667],
       [10852.92666667],
       [10438.55416667],
       [10300.41166667],
       [ 9584.47583333],
       [10092.75166667],
       [10455.73      ],
       [10685.415     ],
       [10569.305     ],
       [10449.62666667],
       [10044.11333333],
       [ 9708.43583333],
       [10021.325     ]])

In [21]:
Y=np.array(df['Predection'])

In [22]:
Y=Y[:-p_day]

In [23]:
Y.shape

(335,)

In [24]:
#split Training

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [27]:
P_day_array =np.array(df.drop(['Predection'],1))[-p_day:]

In [28]:
P_day_array

array([[ 9774.2575    ],
       [ 9725.4025    ],
       [ 9500.32416667],
       [ 9533.97933333],
       [ 9539.7125    ],
       [ 9873.81166667],
       [10088.8       ],
       [10478.90166667],
       [10790.63      ],
       [10826.275     ],
       [11713.16166667],
       [11759.01916667],
       [11703.73833333],
       [11803.88833333],
       [11816.9125    ],
       [11586.1725    ],
       [11377.80416667],
       [11397.80166667],
       [11144.38916667],
       [10450.81333333],
       [ 9988.9475    ],
       [10230.73333333],
       [10292.38333333],
       [10295.1175    ],
       [10605.82583333],
       [10746.50769231],
       [10169.09416667],
       [10030.74666667],
       [10255.9775    ],
       [10158.54083333]])

In [29]:
from sklearn.ensemble import RandomForestRegressor

In [30]:
Rf=RandomForestRegressor(n_estimators=1000,random_state=1)

In [31]:
Rf.fit(X_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=1)

In [33]:
print('Ramdom Forest Accuracy:{:.2f}%'.format(Rf.score(X_test,y_test)*100))

Ramdom Forest Accuracy:83.74%

In [34]:
#Predection

In [35]:
Rf_predict=Rf.predict(X_test)

In [37]:
print(Rf_predict)

[ 6109.60424024 11080.76845494  5571.92337667  4312.49336551
  4231.544215   10403.581821    4041.2000449   6283.28554167
  5554.88870429  5847.73499667  6389.09544833  6279.06982417
  6419.19753667 11162.41246833  6843.9022016  11384.11528917
  4888.42479917  3672.56149442  5121.955535    6165.16252833
  5642.561225    4891.5851616   5853.64465917  6560.344745
  5070.14142417 10085.00973167  6287.80852333  3847.47566891
 10038.17991183  8348.6520575   3842.87701699  7497.1635916
  3891.30989904  5889.19874744 10201.35124417  5049.54687333
  8133.43928333  4219.05895506  6321.48884583  3854.33443987
  4157.09022417  4236.33114583  5281.286785    4501.89176167
  3854.33443987  3955.87532583  3672.48537897  7137.45693071
  5073.29292327  4274.30716333  3494.32608667  6703.2496275
  7937.66544167  4054.9555875  11092.29119859 11125.18104205
  3861.56936615  3672.48537897  3956.91199923  4799.08821
 10966.18057571 12228.16855833  9826.00444167 11112.81569205
  4451.27735613  7130.87321596 10065.9843225 ]

In [38]:
print(y_test)

[ 6310.28416667  8163.66333333  3435.34        4006.11583333
  5277.88333333 11703.73833333  4109.31666667  7817.76833333
  3523.96        3742.94333333  3278.37416667  6568.04076923
  7941.22166667 11713.16166667  5654.35333333 10021.325
  6299.39916667  3652.21166667  5114.85416667  4548.7975
  6387.67416667  5031.475       4293.84083333  7815.13583333
  4309.3375     10230.73333333  6372.06333333  4036.09333333
 11586.1725      7338.52083333  3812.58583333  8005.25083333
  3567.76333333  5718.22916667 10569.305       4106.87166667
  8646.195       5214.27666667  6363.79583333  3827.69083333
  3912.28583333  3458.70333333  5274.14583333  3452.22333333
  3827.4875      3865.7975      3609.86916667  8063.89583333
  5042.51769231  3579.89666667  5281.80916667  6590.96833333
  7756.9575      3933.95416667  9346.0725      8721.645
  3656.73583333  3896.71833333  3922.615       3791.54583333
 11545.63333333 12567.70384615 10685.415      10748.01166667
  4011.36583333  5863.52333333 10292.38333333]

In [39]:
Rf_predict_30=Rf.predict(P_day_array)

In [41]:
print(Rf_predict)

[ 6109.60424024 11080.76845494  5571.92337667  4312.49336551
  4231.544215   10403.581821    4041.2000449   6283.28554167
  5554.88870429  5847.73499667  6389.09544833  6279.06982417
  6419.19753667 11162.41246833  6843.9022016  11384.11528917
  4888.42479917  3672.56149442  5121.955535    6165.16252833
  5642.561225    4891.5851616   5853.64465917  6560.344745
  5070.14142417 10085.00973167  6287.80852333  3847.47566891
 10038.17991183  8348.6520575   3842.87701699  7497.1635916
  3891.30989904  5889.19874744 10201.35124417  5049.54687333
  8133.43928333  4219.05895506  6321.48884583  3854.33443987
  4157.09022417  4236.33114583  5281.286785    4501.89176167
  3854.33443987  3955.87532583  3672.48537897  7137.45693071
  5073.29292327  4274.30716333  3494.32608667  6703.2496275
  7937.66544167  4054.9555875  11092.29119859 11125.18104205
  3861.56936615  3672.48537897  3956.91199923  4799.08821
 10966.18057571 12228.16855833  9826.00444167 11112.81569205
  4451.27735613  7130.87321596 10065.9843225 ]

In [42]:
df.head(30)

          Price   Predection
0   6719.429231  6639.304167
1   6673.274167  6412.459167
2   6719.266154  6468.631667
3   7000.040000  6535.476667
4   7054.276429  6677.342500
5   6932.662500  6550.474167
6   6981.946154  6593.135000
7   7100.946667  6590.968333
8   7247.935385  6562.641667
9   7260.949231  6470.402500
10  7326.852500  6563.628333
11  7113.069231  6568.549167
12  6433.271667  6581.486667
13  6444.804167  6558.537500
14  6366.107500  6618.567692
15  6286.425833  6621.711667
16  6297.877692  6563.009167
17  6296.320833  6248.635833
18  6273.137500  6260.530833
19  6450.179231  6260.645833
20  6499.062500  6299.399167
21  6518.655000  6452.571667
22  6480.644167  6596.618333
23  6400.600833  6596.276154
24  6296.631667  6568.040769
25  6335.826667  6487.444167
26  6418.562667  6488.825833
27  6669.990833  6531.601667
28  6709.312500  6498.485833
29  6710.445000  6481.426000

In [ ]:
s